assistencias/urls.py
from django.urls import path

from . import views
app_name = 'assistencias'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    path('<int:assistencia_id>/detalhe', views.detalhe, name='detalhe'),
    path('<int:assistencia_id>/atualizar', views.atualizar, name='atualizar'),
    path('pesquisarAssistencia', views.pesquisarAssistencia, name='pesquisa_assistencia'),
    path('pesquisarCliente', views.pesquisarCliente, name='pesquisa_cliente'),
    path('pesquisarProduto', views.pesquisarProduto, name='pesquisa_produto'),

    path('<int:cliente_id>/atualizarCliente', views.atualizarCliente, name='atualiza_cliente'),
    path('<int:produto_id>/atualizarProduto', views.atualizarProduto, name='atualiza_produto'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mlpbarreiro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('assistencias/', include('assistencias.urls')),
]

assistencias/models.py
import datetime
from django.db import models
from django.utils import timezone
import logging
logger=logging.getLogger(__name__)

class Assistencia(models.Model):
    produto = models.ForeignKey('Produto', on_delete=models.CASCADE)
    funcionario = models.ForeignKey('Pessoa',related_name="funcionario", on_delete=models.CASCADE)
    cliente = models.ForeignKey('Pessoa',related_name="cliente", on_delete=models.CASCADE)
    topico_text = models.CharField(max_length=50)
    descricao_text = models.TextField(max_length=200)
    pub_date = models.DateField()
    valor = models.DecimalField(decimal_places=2,max_digits=5, blank=True)
    foto = models.FileField(blank=True)
    pago_bol = models.BooleanField(default=False)

    @property
    def get(self):
        data = {'produto':self.produto.id,'funcionario':self.funcionario.nome_text,
                'cliente':self.cliente.nome_text,'topico_text':self.topico_text,
                'descricao_text':self.descricao_text,'valor':self.valor,
                'pago_bol':self.pago_bol}
        return data

    def __str__(self):
        return self.topico_text

    @property
    def sendAssistencia(self):
        id=self.id
        produto = self.produto.descricao_text
        funcionario = self.funcionario.nome_text
        cliente = self.cliente.nome_text
        topico = self.topico_text
        descricao = self.descricao_text
        valor = float(self.valor)
        pago = self.pago_bol
        jsonObj = {'id':id,'produto':produto,'cliente':cliente,'topico':topico,'descricao':descricao,
                   'valor':valor,'pago':pago}
        logger.error("borala",jsonObj)
        return jsonObj


class Produto(models.Model):
    marca_text = models.CharField(max_length=200,blank=True)
    numserie_text= models.CharField(max_length=200,blank=True)
    descricao_text = models.CharField(max_length=200)
    assistencias = models.ManyToManyField(Assistencia,related_name="assistencias",blank=True)

    def __str__(self):
        return self.descricao_text

class Pessoa(models.Model):
    nome_text = models.CharField(max_length=50,blank=True,null=True)
    telefone_text = models.IntegerField(blank=True,null=True)
    email_text = models.EmailField(blank=True,null=True)
    morada_text = models.CharField(max_length=50,blank=True,null=True)
    localidade_text = models.CharField(max_length=50,blank=True,null=True)
    codigo_postal_text = models.CharField(max_length=10,blank=True,null=True)
    assistencias = models.ManyToManyField(Assistencia,blank=True,null=True)

    def __str__(self):
        return self.nome_text

class Pedido(models.Model):
    cliente = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    pedido_text = models.CharField(max_length=200)
    valor = models.DecimalField(decimal_places=2,max_digits=5,blank=True)
    foto = models.FileField(blank=True)

    def __str__(self):
        return self.pedido_text

assistencias/forms.py
from django import forms
from django.forms import ModelForm
from assistencias.models import Assistencia, Pessoa, Produto

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

class AssistenciaForm(ModelForm):
    class Meta:
        model = Assistencia
        fields = ['produto','funcionario','cliente','topico_text',
                  'descricao_text','pub_date','valor','pago_bol']

class PesquisaClienteForm(ModelForm):
    class Meta:
        model = Pessoa
        fields = ['id','nome_text','telefone_text','email_text','morada_text',
                  'localidade_text','codigo_postal_text']

class PesquisaProdutoForm(ModelForm):
    class Meta:
        model = Produto
        fields = ['marca_text','numserie_text','descricao_text']


class pesquisaAssistenciaForm(forms.Form):
    pub_date_init = forms.DateField(required=False)
    pub_date_fim = forms.DateField(required=False)
    produto = forms.IntegerField(label="Id Produto",required=False)
    funcionario = forms.CharField(label='Nome Funcionario', max_length=100,required=False)
    cliente = forms.CharField(label="Nome Cliente", max_length=100,required=False)
    topico_text = forms.CharField(label="Topico", max_length=100,required=False)
    descricao_text = forms.CharField(label="descrição texto", widget=forms.Textarea,required=False)
    valor = forms.DecimalField(required=False)
    pago_bol = forms.BooleanField(required=False)



class pesquisaNome(forms.Form):
    cliente = forms.CharField(label="Nome Cliente", max_length=100,required=False)

assistencias/views.py
from django.core import serializers
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect, JsonResponse
from .models import Assistencia, Produto, Pedido, Pessoa
from django.views import generic
from django.db.models import Q
from .forms import NameForm, AssistenciaForm, \
    pesquisaAssistenciaForm, PesquisaClienteForm, PesquisaProdutoForm
from datetime import datetime, date
import logging, json

logger=logging.getLogger(__name__)
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest_assistencia_list'

    def get_queryset(self):
        """Return the last five published assistencias."""
        return Assistencia.objects.order_by('-pub_date')[:50]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = pesquisaAssistenciaForm()
        context['formCliente'] = PesquisaClienteForm()
        context['formProduto'] = PesquisaProdutoForm()
        return context

def detail(request, question_id):
    return render(request,'assistencias/index.html')

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

def assistencias(request):
    return render(request,'assistencias.html',{
        'entries':Assistencia.objects.all()
    })

def detalhe(request, assistencia_id):
    assistencia = Assistencia.objects.get(pk=assistencia_id)
    form = AssistenciaForm(instance=assistencia)
    if form.is_valid():
        logger.error("VALIDO")
        return render(request,'detalhes.html',{
        'assistencia':assistencia,
        'form':form})
    else:
        return render(request,'detalhes.html',{
        'assistencia':assistencia,
        'form':form})

def atualizar(request, assistencia_id):
    if request.method == 'POST':
        assistencia = Assistencia.objects.get(pk=assistencia_id)
        form = AssistenciaForm(request.POST,instance=assistencia)
        form.save()
        return HttpResponse("THANKS")
    else:
        return HttpResponse("NOT VALID")

def pesquisaPessoa(request):
    body = request.POST
    assistencias = Assistencia.objects.filter(cliente__nome_text__contains=body["nome"])
    arrayAssistencias=[]
    for assistencia in assistencias:
        object = assistencia.sendAssistencia
        arrayAssistencias.append(object)
    return JsonResponse(arrayAssistencias,safe=False)

def pesquisarAssistencia(request):
    requestForm = pesquisaAssistenciaForm(request.POST)
    try:
        dataInit = datetime.strptime(requestForm['pub_date_init'].value(),'%Y-%m-%d')
    except ValueError:
        dataInit = date(1990,1,1)

    try:
        dataFim = datetime.strptime(requestForm['pub_date_fim'].value(),'%Y-%m-%d')
    except ValueError:
        dataFim = date(2100,1,1)

    assistencias = Assistencia.objects.filter(cliente__nome_text__icontains=requestForm['cliente'].value(),
                                              funcionario__nome_text__icontains=requestForm['funcionario'].value(),
                                              topico_text__icontains=requestForm['topico_text'].value(),
                                              descricao_text__icontains=requestForm['descricao_text'].value(),
                                              valor__icontains=requestForm['valor'].value(),
                                              pub_date__gte=dataInit,
                                              pub_date__lte=dataFim
                                              )

    logger.error(assistencias)
    return render(request,'pesquisaAssistencias.html',{'assistencias':assistencias, 'formAssistencia':pesquisaAssistenciaForm(),
                                                       'formCliente':PesquisaClienteForm,'formProduto':PesquisaProdutoForm})

def pesquisarCliente(request):
    if 'novoCliente' in request.POST:
        if request.POST['nome_text']=="":
            return HttpResponse("Nome Invalido")
        else:
            form = PesquisaClienteForm(request.POST)
            form.save()
            return HttpResponse("Cliente Adicionado com sucesso")
    else:
        requestForm = PesquisaClienteForm(request.POST)
        clientes = Pessoa.objects.filter(nome_text__icontains=requestForm['nome_text'].value())
        return render(request,'pesquisaClientes.html',{'clientes':clientes,
                      'formAssistencia':pesquisaAssistenciaForm(),'formCliente':PesquisaClienteForm(),
                        'formProduto':PesquisaProdutoForm()})

def pesquisarProduto(request):
    requestForm = PesquisaProdutoForm(request.POST)
    produtos = Produto.objects.filter(descricao_text__icontains=requestForm['descricao_text'].value())
    return render(request,'pesquisaProdutos.html',{'produtos':produtos,
                  'formAssistencia':pesquisaAssistenciaForm(),'formCliente':PesquisaClienteForm(),
                    'formProduto':PesquisaProdutoForm()})

def atualizarCliente(request,cliente_id):
    if request.method=="GET":
        cliente=Pessoa.objects.get(pk=cliente_id)
        form = PesquisaClienteForm(instance=cliente)
        logger.error(form)
        return render(request,'atualizarCliente.html',{'form':form, 'cliente':cliente, 'formAssistencia':AssistenciaForm()})
    elif request.method=="POST":
        cliente = Pessoa.objects.get(pk=cliente_id)
        form = PesquisaClienteForm(request.POST,instance=cliente)
        form.save()
        return HttpResponse("Cliente Salvo")

def atualizarProduto(request,produto_id):
    if request.method=="GET":
        produto=Produto.objects.get(pk=produto_id)
        form = PesquisaProdutoForm(instance=produto)
        logger.error(form)
        return render(request,'atualizarProduto.html',{'form':form, 'produto':produto})
    elif request.method=="POST":
        produto = Produto.objects.get(pk=produto_id)
        form = PesquisaProdutoForm(request.POST,instance=produto)
        form.save()
        return HttpResponse("Produto Salvo")

assistencias/templates/assistencias.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'assistencias/assistencias.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'assistencias/style.css' %}" />

{% csrf_token %}
<script type="text/javascript">
// using jQuery
var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
</script>

<p>ASSISTENCIAS</p>
<ul class="menu">
  <li><a href="#Pedidos">Pedidos</a></li>
  <li><a href="{% url 'assistencias:pedidos_assistencia' %}">Assistencias</a></li>
  <li><a href="#Contactos">Contactos</a></li>
  <li><a href="#Sobre">Sobre</a></li>
</ul>

<form class="form-inline" id="form_pessoas" action="">
    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" class="form-control" name="email">
    </div>
    <div class="form-group">
      <label for="nome">Nome:</label>
      <input type="text" class="form-control" name="nome">
    </div>
    <div class="form-group">
        <label for="telefone">Telefone</label>
        <input type="tel" class="form-control" name="telefone">
    </div>
        <label for="morada">Morada</label>
        <input type="morada" class="form-control" id="morada">
    <button type="button" class="btn btn-default" id="form_pessoas_novo" >Novo</button>
    <button type="buton" class="btn btn-default" id="form_pessoas_procurar">Procurar</button>
</form>



{% for assistencia in latest_assistencia_list %}
  <tr onclick="document.location = '{% url 'assistencias:detalhe' assistencia.id%}'">
    <td>{{assistencia.cliente}}</td>
    <td>{{assistencia.topico_text}}</td>
    <td>{{assistencia.descricao_text}}</td>
    <td>{{assistencia.valor}}</td>
    <td>{{assistencia.pub_date}}</td>
  </tr>
{% endfor %}
</tbody>
</table>

assistencias/templates/atualizarCliente.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'assistencias/style.css' %}" />
<p>ASSISTENCIAS</p>
<ul class="menu">
  <li><a href="#Pedidos">Pedidos</a></li>
  <li><a href="{% url 'assistencias:index' %}">Assistencias</a></li>
  <li><a href="#Contactos">Contactos</a></li>
  <li><a href="#Sobre">Sobre</a></li>
</ul>


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'assistencias:atualiza_cliente' cliente.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Atualizar" />
</form>

<form action="{% url 'assistencias:nova_assistencia' cliente.id%}" method="post">
    {% csrf_token %}
    {{formAssistencia.as_p}}
    <input type="submit" value="Submeter Pedido" />
</form>

assistencias/templates/atualizarProduto.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'assistencias/style.css' %}" />
<p>ASSISTENCIAS</p>
<ul class="menu">
  <li><a href="#Pedidos">Pedidos</a></li>
  <li><a href="{% url 'assistencias:index' %}">Assistencias</a></li>
  <li><a href="#Contactos">Contactos</a></li>
  <li><a href="#Sobre">Sobre</a></li>
</ul>


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'assistencias:atualiza_produto' produto.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Atualizar" />
</form>

assistencias/templates/detalhes.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'assistencias/style.css' %}" />
<p>ASSISTENCIAS</p>
<ul class="menu">
  <li><a href="#Pedidos">Pedidos</a></li>
  <li><a href="{% url 'assistencias:index' %}">Assistencias</a></li>
  <li><a href="#Contactos">Contactos</a></li>
  <li><a href="#Sobre">Sobre</a></li>
</ul>


<h1>{{ assistencia.topico_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'assistencias:atualizar' assistencia.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Atualizar" />
</form>

assistencias/templates/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'assistencias/style.css' %}" />

<ul class="menu">
  <li><a href="{% url 'assistencias:index' %}">Assistencias</a></li>
  <li><a href="#Pedidos">Pedidos</a></li>
  <li><a href="#Contactos">Contactos</a></li>
  <li><a href="#Sobre">Sobre</a></li>
</ul>

<table id="tabela_assistencias">
  <th>Cliente</th>
  <th>Topico</th>
  <th>Descricao</th>
  <th>Valor</th>
  <th>Data</th>
<tbody>
<div class="container">
  <div class="formAssistencia">
  <form action="{% url 'assistencias:pesquisa_assistencia'%}" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Pesquisar Assistencia" />
  </form>
  </div>

  <div class="formClientes">
    <form action="{% url 'assistencias:pesquisa_cliente'%}" method="post">
      {% csrf_token %}
      {{formCliente.as_p}}
      <input type="radio" name="novoCliente" value="Novo Cliente"> Novo Cliente<br>
      <input type="submit" value="Pesquisa/Adicionar Cliente" />
    </form>
  </div>

  <div class="formProdutos">
    <form action="{% url 'assistencias:pesquisa_produto'%}" method="post">
      {% csrf_token %}
      {{formProduto.as_p}}
      <input type="submit" value="Pesquisar Produto" />
      <input type="button" value="Novo Produto" onclick="document.location = '{% url 'assistencias:index' %}'">
    </form>
  </div>
</div>

{% for assistencia in latest_assistencia_list %}
  <tr onclick="document.location = '{% url 'assistencias:detalhe' assistencia.id%}'">
    <td>{{assistencia.cliente}}</td>
    <td>{{assistencia.topico_text}}</td>
    <td>{{assistencia.descricao_text}}</td>
    <td>{{assistencia.valor}}</td>
    <td>{{assistencia.pub_date}}</td>
  </tr>
{% endfor %}
</tbody>
</table>

assistencias/templates/pesquisaAssistencias.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'assistencias/style.css' %}" />

<ul class="menu">
  <li><a href="{% url 'assistencias:index' %}">Assistencias</a></li>
  <li><a href="#Pedidos">Pedidos</a></li>
  <li><a href="#Contactos">Contactos</a></li>
  <li><a href="#Sobre">Sobre</a></li>
</ul>

<table id="tabela_assistencias">
  <th>cliente</th>
  <th>topico</th>
  <th>descricao</th>
  <th>valor</th>
    <th>Data</th>
<tbody>

<div class="container">
  <div class="formAssistencia">
  <form action="{% url 'assistencias:pesquisa_assistencia'%}" method="post">
      {% csrf_token %}
      {{formAssistencia.as_p}}
      <input type="submit" value="Pesquisa" />
  </form>
  </div>

  <div class="formClientes">
    <form action="{% url 'assistencias:pesquisa_cliente'%}" method="post">
      {% csrf_token %}
      {{formCliente.as_p}}
      <input type="radio" name="novoCliente" value="Novo Cliente"> Novo Cliente<br>
      <input type="submit" value="Pesquisa/Adicionar Clientes" />
    </form>
  </div>

  <div class="formProdutos">
    <form action="{% url 'assistencias:pesquisa_produto'%}" method="post">
      {% csrf_token %}
      {{formProduto.as_p}}
      <input type="submit" value="Pesquisa" />
      <input type="button" value="Novo Produto" onclick="document.location = '{% url 'assistencias:index' %}'">
  </div>
</div>

{% for assistencia in assistencias %}
  <tr onclick="document.location = '{% url 'assistencias:detalhe' assistencia.id%}'">
    <td>{{assistencia.cliente}}</td>
    <td>{{assistencia.topico_text}}</td>
    <td>{{assistencia.descricao_text}}</td>
    <td>{{assistencia.valor}}</td>
      <td>{{assistencia.pub_date}}</td>
  </tr>
{% endfor %}
</tbody>
</table>

assistencias/templates/pesquisaClientes.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'assistencias/style.css' %}" />

<ul class="menu">
  <li><a href="{% url 'assistencias:index' %}">Assistencias</a></li>
  <li><a href="#Pedidos">Pedidos</a></li>
  <li><a href="#Contactos">Contactos</a></li>
  <li><a href="#Sobre">Sobre</a></li>
</ul>

<table id="tabela_assistencias">
    <th>id</th>
  <th>nome_text</th>
  <th>telefone_text</th>
  <th>email_text</th>
  <th>morada_text</th>
  <th>localidade_text</th>
   <th>codigo_postal_text</th>
<tbody>
<div class="container">
  <div class="formAssistencia">
  <form action="{% url 'assistencias:pesquisa_assistencia'%}" method="post">
      {% csrf_token %}
      {{formAssistencia.as_p}}
      <input type="submit" value="Pesquisa" />
  </form>
  </div>

  <div class="formClientes">
    <form action="{% url 'assistencias:pesquisa_cliente'%}" method="post">
      {% csrf_token %}
      {{formCliente.as_p}}
      <input type="radio" name="novoCliente" value="Novo Cliente"> Novo Cliente<br>
      <input type="submit" value="Pesquisa/Adicionar Clientes" />
    </form>
  </div>

  <div class="formProdutos">
    <form action="{% url 'assistencias:pesquisa_produto'%}" method="post">
      {% csrf_token %}
      {{formProduto.as_p}}
      <input type="submit" value="Pesquisa" />
      <input type="button" value="Novo Produto" onclick="document.location = '{% url 'assistencias:index' %}'">
  </div>
</div>

{% for cliente in clientes %}
  <tr onclick="document.location = '{% url 'assistencias:atualiza_cliente' cliente.id%}'">
      <td>{{cliente.id}}</td>
    <td>{{cliente.nome_text}}</td>
    <td>{{cliente.telefone_text}}</td>
    <td>{{cliente.email_text}}</td>
    <td>{{cliente.morada_text}}</td>
    <td>{{cliente.localidade_text}}</td>
      <td>{{cliente.codigo_postal_text}}</td>
  </tr>
{% endfor %}
</tbody>
</table>

assistencias/templates/pesquisaProdutos.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'assistencias/style.css' %}" />

<ul class="menu">
  <li><a href="{% url 'assistencias:index' %}">Assistencias</a></li>
  <li><a href="#Pedidos">Pedidos</a></li>
  <li><a href="#Contactos">Contactos</a></li>
  <li><a href="#Sobre">Sobre</a></li>
</ul>

<table id="tabela_assistencias">
    <th>id</th>
  <th>nome_text</th>
  <th>telefone_text</th>
  <th>email_text</th>
  <th>morada_text</th>
  <th>localidade_text</th>
   <th>codigo_postal_text</th>
<tbody>
<div class="container">
  <div class="formAssistencia">
  <form action="{% url 'assistencias:pesquisa_assistencia'%}" method="post">
      {% csrf_token %}
      {{formAssistencia.as_p}}
      <input type="submit" value="Pesquisa" />
  </form>
  </div>

  <div class="formClientes">
    <form action="{% url 'assistencias:pesquisa_cliente'%}" method="post">
      {% csrf_token %}
      {{formCliente.as_p}}
      <input type="submit" value="Pesquisa" />
      <input type="button" value="Novo Cliente" onclick="document.location = '{% url 'assistencias:index' %}'">
  </div>

  <div class="formProdutos">
    <form action="{% url 'assistencias:pesquisa_produto'%}" method="post">
      {% csrf_token %}
      {{formProduto.as_p}}
      <input type="submit" value="Pesquisa" />
      <input type="button" value="Novo Produto" onclick="document.location = '{% url 'assistencias:index' %}'">
  </div>
</div>

{% for produto in produtos %}
  <tr onclick="document.location = '{% url 'assistencias:atualiza_produto' produto.id%}'">
    <td>{{produto.id}}</td>
    <td>{{produto.marca_text}}</td>
    <td>{{produto.numserie_text}}</td>
    <td>{{produto.descricao_text}}</td>
  </tr>
{% endfor %}
</tbody>
</table>